<?xml version="1.0"?>
<package format="2">
  <name>sz_indoor_traj_router</name>
  <version>0.0.0</version>
  <description>The sz_indoor_traj_router package</description>

  <maintainer email="549452991@qq.com">csk</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>roscpp</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>sz_indoor_controller</depend>

</package>
